# Generated by Django 3.1.6 on 2021-02-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0002_auto_20210210_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='publish',
        ),
        migrations.RemoveField(
            model_name='article',
            name='status',
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default='alireza', max_length=50),
        ),
    ]
